### PR TITLE
Add controller option for flash notices

### PR DESCRIPTION
**Pull request by samrayner**

### CODE REVIEW

**Comment by samrayner** [comment]
Thoughts on this @Haar?

**Comment by Haar** [comment]
I was going to add some tests for it - just a basic controller with the option disabled vs default of showing flash.

**Comment by samrayner** [comment]
👍 I'll leave it with you as you would probably want to refactor my stuff anyway.

**Comment by samrayner** [comment]
@Haar Please can you look at this soon?

**Pull request closed without merging**
